services:
  web:
    build: .
    container_name: livekit-meet-auth
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./config:/app/config
      - ./data:/app/data
      - ./static:/app/static
